name: Build and Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Bump Version & Release"]
    types:
      - completed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
            build_cmd: flutter build apk --release
            output: build/app/outputs/flutter-apk/app-release.apk
            ext: apk
          - platform: windows
            os: windows-latest
            build_cmd: flutter build windows --release
            output: build/windows/x64/runner/Release/app.exe
            ext: exe
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build ${{ matrix.platform }}
        run: ${{ matrix.build_cmd }}
      - name: Move output to build dir with version
        shell: bash
        run: |
          VERSION=$(cat pubspec.yaml | grep version: | awk '{print $2}')
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            OUT_VERSION=${GITHUB_REF#refs/tags/}
          else
            OUT_VERSION=${VERSION}-build.${{ github.run_number }}
          fi
          mkdir -p dist
          if [ "${{ matrix.platform }}" = "android" ]; then
            mv ${{ matrix.output }} dist/admincraft-android-${OUT_VERSION}.${{ matrix.ext }}
          else
            mv ${{ matrix.output }} dist/admincraft-windows-${OUT_VERSION}.${{ matrix.ext }}
          fi
      - name: Upload build as workflow artifact (optional)
        if: false # disabled to save space
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get version
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            PRERELEASE=false
          else
            VERSION=$(cat pubspec.yaml | grep version: | awk '{print $2}')-build.${{ github.run_number }}
            PRERELEASE=true
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "prerelease=$PRERELEASE" >> $GITHUB_OUTPUT
      - name: Collect built files
        run: |
          mkdir -p dist
          # Copy from all runners (if using a shared storage or upload step)
          # In this setup, the files should be committed or otherwise made available
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          prerelease: ${{ steps.get_version.outputs.prerelease }}
          files: |
            dist/admincraft-android-${{ steps.get_version.outputs.version }}.apk
            dist/admincraft-windows-${{ steps.get_version.outputs.version }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
