name: Build and Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Bump Version & Release"]
    types:
      - completed

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build Android APK
        run: flutter build apk --release
      - name: Archive Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/apk/release/app-release.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build Windows Executable
        run: flutter build windows --release
      - name: Archive Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build/windows/x64/runner/Release/

  release:
    needs: [build-android, build-windows]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: dist
      - name: Download Windows Executable
        uses: actions/download-artifact@v4
        with:
          name: windows-exe
          path: dist/Release
      - name: Get version
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            PRERELEASE=false
          else
            VERSION=$(cat pubspec.yaml | grep version: | awk '{print $2}')-build.${{ github.run_number }}
            PRERELEASE=true
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "prerelease=$PRERELEASE" >> $GITHUB_OUTPUT
      - name: Rename APK with version
        run: mv dist/app-release.apk dist/admincraft-android-${{ steps.get_version.outputs.version }}.apk
      - name: Zip Windows Executable with version
        run: |
          cd dist/Release
          zip -r ../../admincraft-windows-${{ steps.get_version.outputs.version }}.zip .
          cd ../../
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          prerelease: ${{ steps.get_version.outputs.prerelease }}
          files: |
            dist/admincraft-android-${{ steps.get_version.outputs.version }}.apk
            dist/admincraft-windows-${{ steps.get_version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
