name: Bump Version & Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type (major, minor, patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Bump version (pubspec)
        run: |
          BUMP_TYPE="${{ github.event.inputs.bump }}"
          VERSION=$(grep '^version:' pubspec.yaml | head -n1 | awk '{print $2}' | cut -d'+' -f1)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          if [ "$BUMP_TYPE" = "major" ]; then
            MAJOR=$((MAJOR+1)); MINOR=0; PATCH=0
          elif [ "$BUMP_TYPE" = "minor" ]; then
            MINOR=$((MINOR+1)); PATCH=0
          else
            PATCH=$((PATCH+1))
          fi
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          yq e -i ".version = \"$NEW_VERSION\"" pubspec.yaml
          echo "Bumped version to $NEW_VERSION"
      - name: Commit and tag version bump
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | head -n1 | awk '{print $2}')
          git add pubspec.yaml
          git commit -m "chore: bump version to $VERSION"
          git tag v$VERSION
      - name: Push changes and tag
        run: |
          git push origin HEAD:main
          git push origin --tags
